name: Deploy
on:
  push:
    branches:
      - main

jobs:
  environment: LiveDeploy
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use node 22
        uses: actions/setup-node@v5
        with:
          node-version: '22.16'
          cache: 'npm'
      - run: npm ci
      - run: npm run cdk -- deploy
