name: Unit Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use node 16
        uses: actions/setup-node@v5
        with:
          node-version: '16.20'
          cache: 'npm'
      - run: npm ci
      - run: npm test
